# Generated by Django 2.2 on 2020-10-07 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
